# Generated by Django 2.0.2 on 2018-02-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_data',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='register_data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
