# Generated by Django 2.0.2 on 2018-02-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_inline',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='未命名', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.BigIntegerField(default=0),
        ),
    ]
